<?php

const BGA_GAMESTATE_GAMEVERSION = 300;
/*
 * Game Constants
 */

const TURN_MAX = 10;
const TOKEN_SETUP_NB = 15;
const MAX_COMMON_ACTIONS_BY_TURN = 2;
const MAX_PERSONAL_ACTIONS_BY_TURN = TURN_MAX;

const COLUMN_MIN = 1;
const COLUMN_MAX = 10;
const ROW_MIN = 1;
const ROW_MAX = 10;
const ROW_START = ROW_MIN;
//55 max : if we go from A1 to J10, from column 1, then 3, then 5, then 7, then 9
//const MAX_MOVES_TO_REACH_A_PLACE = (COLUMN_MAX -COLUMN_MIN +1 ) /2 *(1+ (ROW_MAX -ROW_MIN +1)  );

//A5
const FIRST_TOKEN_ROW = 1;
const FIRST_TOKEN_COLUMN = 5;

// 8 : an orthogonal grid with 4 neighbours + 4 in diagonal
const MAX_GRID_NEIGHBOURS = 8;

//We need 3 aligned tokens to gain special actions
const NB_ALIGNED_TOKENS_TO_GAIN_ACTIONS = 3;
const MAX_SPECIAL_ACTIONS = 9;
const NB_TOKENS_PREDICTION = 3;
const NB_TOKENS_MIN_JEALOUSY = 5;

const WIND_DIR_NORTH = 'N';
const WIND_DIR_SOUTH = 'S';
const WIND_DIR_EAST = 'E';
const WIND_DIR_WEST = 'W';
const WIND_DIR_UNKNOWN = 'U';
const WIND_DIRECTIONS = [WIND_DIR_NORTH,WIND_DIR_SOUTH,WIND_DIR_EAST,WIND_DIR_WEST,WIND_DIR_UNKNOWN];

const SCORE_DIFFICULTY_1 = 5;
const SCORE_DIFFICULTY_2 = 10;
const SCORE_DIFFICULTY_3 = 20;
const SCORE_DIFFICULTY_4 = 40;
const SCORE_JOKER_USED = -5;
const SCORE_PER_ACTION = 1;
const SCORE_PER_RECRUIT = 1;
//Not specified by the rules : but I add this to separate '0' score when fullfil easy game with joker VS loosing
const SCORE_FAIL = -1;

/* TOKEN TYPES : stigmerians, then pollens*/
const TOKEN_STIG_BLUE =     1;
const TOKEN_STIG_YELLOW =   2;
const TOKEN_STIG_RED =      3;
const TOKEN_STIG_ORANGE =   4;
const TOKEN_STIG_GREEN =    5;
const TOKEN_STIG_VIOLET =   6;
const TOKEN_STIG_BROWN =    7;
const TOKEN_STIG_WHITE =    8;
const TOKEN_STIG_BLACK =    9;
const STIG_PRIMARY_COLORS = [TOKEN_STIG_BLUE,TOKEN_STIG_RED,TOKEN_STIG_YELLOW, ];
const STIG_COLORS = [TOKEN_STIG_BLUE,TOKEN_STIG_RED,TOKEN_STIG_YELLOW,
    TOKEN_STIG_ORANGE,TOKEN_STIG_GREEN,TOKEN_STIG_VIOLET,
    TOKEN_STIG_BROWN,TOKEN_STIG_WHITE,TOKEN_STIG_BLACK,
];
const TOKEN_POLLEN_BLUE =     11;
const TOKEN_POLLEN_YELLOW =   12;
const TOKEN_POLLEN_RED =      13;
const TOKEN_POLLEN_ORANGE =   14;
const TOKEN_POLLEN_GREEN =    15;
const TOKEN_POLLEN_VIOLET =   16;
const TOKEN_POLLEN_BROWN =    17;
const TOKEN_POLLEN_WHITE =    18;
const TOKEN_POLLEN_BLACK =    19;
const TOKEN_POLLENS = [
    TOKEN_STIG_BLUE     => TOKEN_POLLEN_BLUE    ,
    TOKEN_STIG_YELLOW   => TOKEN_POLLEN_YELLOW  ,
    TOKEN_STIG_RED      => TOKEN_POLLEN_RED     ,
    TOKEN_STIG_ORANGE   => TOKEN_POLLEN_ORANGE  ,
    TOKEN_STIG_GREEN    => TOKEN_POLLEN_GREEN   ,
    TOKEN_STIG_VIOLET   => TOKEN_POLLEN_VIOLET  ,
    TOKEN_STIG_BROWN    => TOKEN_POLLEN_BROWN   ,
    TOKEN_STIG_WHITE    => TOKEN_POLLEN_WHITE   ,
    TOKEN_STIG_BLACK    => TOKEN_POLLEN_BLACK   ,
];

/* TOKEN LOCATIONS */ 
const TOKEN_LOCATION_PLAYER_DECK = 'player_deck_';//To be followed by pid in order to shuffle separately
const TOKEN_LOCATION_PLAYER_RECRUIT = 'player_recruit';
const TOKEN_LOCATION_PLAYER_BOARD = 'player_board';
const TOKEN_LOCATION_OUT = 'OUT';
const TOKEN_LOCATION_CENTRAL_RECRUIT = 'central_recruit';
const TOKEN_LOCATION_CENTRAL_RECRUIT_TOPLACE = 'central_toplace';
const TOKEN_LOCATION_CENTRAL_BOARD = 'central_board';

/* TOKEN STATES */ 
const TOKEN_STATE_STIGMERIAN = 0;
const TOKEN_STATE_POLLEN = 1;

/** ACTIONS COSTS */
const ACTION_COST_MOVE = 1;
const ACTION_COST_LAND = 1;
const ACTION_COST_CENTRAL_LAND = 1;
const ACTION_COST_CENTRAL_MOVE = 1;
const ACTION_COST_MODIFIER_INSPIRACTRICE = 2;
const ACTION_COST_CENTRAL_RECRUIT = 2;

/** ACTIONS TYPES */
const ACTION_TYPE_LASTDRIFT_PERSONAL = 1;
const ACTION_TYPE_LASTDRIFT_CENTRAL = 2;
const ACTION_TYPE_LASTDRIFT_OPPONENT = 3;
const ACTION_TYPE_MIXING = 10;
const ACTION_TYPE_COMBINATION = 11;
const ACTION_TYPE_FULGURANCE = 12;
const ACTION_TYPE_CHOREOGRAPHY = 13;
const ACTION_TYPE_DIAGONAL = 14;
const ACTION_TYPE_SWAP = 15;
const ACTION_TYPE_MOVE_FAST = 16;
const ACTION_TYPE_WHITE = 20;
const ACTION_TYPE_BLACK = 21;
const ACTION_TYPE_TWOBEATS = 22;
const ACTION_TYPE_REST = 23;
//Neither Seen Nor Known, 'Ni Vu ni Connu'
const ACTION_TYPE_NSNK = 24;
const ACTION_TYPE_COPY = 25;
const ACTION_TYPE_PREDICTION = 26;
const ACTION_TYPE_MIMICRY = 27;
const ACTION_TYPE_FOGDIE = 28;
const ACTION_TYPE_PILFERER = 29;
const ACTION_TYPE_SOWER = 30;
const ACTION_TYPE_CHARMER = 31;
const ACTION_TYPE_JEALOUSY = 32;
const ACTION_TYPES = [
    ACTION_TYPE_MIXING      ,
    ACTION_TYPE_COMBINATION ,
    ACTION_TYPE_FULGURANCE  ,
    ACTION_TYPE_CHOREOGRAPHY,    
    ACTION_TYPE_DIAGONAL    ,
    ACTION_TYPE_SWAP        ,
    ACTION_TYPE_MOVE_FAST   ,
    ACTION_TYPE_WHITE       ,
    ACTION_TYPE_BLACK       ,
    ACTION_TYPE_TWOBEATS    ,
    ACTION_TYPE_REST        ,
    ACTION_TYPE_NSNK        ,
    ACTION_TYPE_COPY        ,
    ACTION_TYPE_PREDICTION  ,
    ACTION_TYPE_MIMICRY     ,
    ACTION_TYPE_FOGDIE      ,
    ACTION_TYPE_PILFERER    ,
    ACTION_TYPE_SOWER       ,
    ACTION_TYPE_CHARMER     ,
    ACTION_TYPE_JEALOUSY    ,
];
const ACTION_VS_TYPES = [
    ACTION_TYPE_PILFERER    ,
    ACTION_TYPE_SOWER       ,
    //Don't make charmer lockable during turn
    //ACTION_TYPE_CHARMER     ,
    //ACTION_TYPE_JEALOUSY
];


/** ACTION DATAS */
const FULGURANCE_NB_TOKENS = 5;
const CHOREOGRAPHY_NB_TURNS_BEFORE = 2;

/** ACTIONS STATES */
const ACTION_LOCATION_PLAYER_BOARD = 'P';//just for the Pieces engine
const ACTION_STATE_UNLOCKED_FOREVER = 0;
const ACTION_STATE_LOCKED = 1;
const ACTION_STATE_LOCKED_FOR_TURN = 2;
const ACTION_STATE_UNLOCKED_FOR_ONCE_GAME = 3;
const ACTION_STATE_UNLOCKED_FOR_ONCE_PER_TURN = 4;


/** DICE FACES */
const NORTH_RED =   1;
const NORTH_BROWN = 2;
const SOUTH_GREEN = 3;
const SOUTH_BLUE =  4;
const EAST_YELLOW = 5;
const EAST_WHITE =  6;
const WEST_VIOLET = 7;
const WEST_ORANGE = 8;
const X_RED =       9;
const X_BLUE =      10;
const X_YELLOW =    11;
const BLACK_NIGHT = 12;


/*
 * Game options
 */ 
// BGA OPTION
const OPTION_GAMESTATE_RATING_MODE = 201; 
const OPTION_GAMESTATE_RATING_MODE_TRAINING = 1;

const OPTION_MODE = 100;
const OPTION_MODE_DISCOVERY = 1;
const OPTION_MODE_NORMAL = 2;
const OPTION_MODE_COMPETITIVE = 3;
const OPTION_MODE_NOLIMIT = 4;
const OPTION_MODE_CHALLENGE = 5;

const OPTION_FLOWER = 101;
const OPTION_FLOWER_VERTIGHAINEUSE = 1;
const OPTION_FLOWER_MARONNE = 2;
const OPTION_FLOWER_SIFFLOCHAMP = 3;
const OPTION_FLOWER_DENTDINE = 4;
const OPTION_FLOWER_INSPIRACTRICE = 5;
const OPTION_FLOWER_COMPETITIVE = 6;
const OPTION_FLOWER_NO_LIMIT = 7;
const OPTION_FLOWER_RANDOM = 10;
const OPTION_FLOWER_VALUES = [
    OPTION_FLOWER_VERTIGHAINEUSE,
    OPTION_FLOWER_MARONNE,
    OPTION_FLOWER_SIFFLOCHAMP,
    OPTION_FLOWER_DENTDINE,
    OPTION_FLOWER_INSPIRACTRICE,
    OPTION_FLOWER_COMPETITIVE,
    OPTION_FLOWER_NO_LIMIT,
];

const OPTION_DIFFICULTY = 102;
const OPTION_DIFFICULTY_1 = 1;
const OPTION_DIFFICULTY_2 = 2;
const OPTION_DIFFICULTY_3 = 3;
const OPTION_DIFFICULTY_4 = 4;
const OPTION_DIFFICULTY_RANDOM = 10;
const OPTION_DIFFICULTY_VALUES = [
    OPTION_DIFFICULTY_1,
    OPTION_DIFFICULTY_2,
    OPTION_DIFFICULTY_3,
    //OPTION_DIFFICULTY_4, -> only NL
];
const OPTION_DIFFICULTY_NL = 103;
const OPTION_DIFFICULTY_ALL = 104;

const OPTION_SCHEMA_V1 = 110;
const OPTION_SCHEMA_V2 = 111;
const OPTION_SCHEMA_V3 = 112;
const OPTION_SCHEMA_M1 = 113;
const OPTION_SCHEMA_M2 = 114;
const OPTION_SCHEMA_M3 = 115;
const OPTION_SCHEMA_S1 = 116;
const OPTION_SCHEMA_S2 = 117;
const OPTION_SCHEMA_S3 = 118;
const OPTION_SCHEMA_D1 = 119;
const OPTION_SCHEMA_D2 = 120;
const OPTION_SCHEMA_D3 = 121;
const OPTION_SCHEMA_I1 = 122;
const OPTION_SCHEMA_I2 = 123;
const OPTION_SCHEMA_I3 = 124;
const OPTION_SCHEMA_C1 = 125;
const OPTION_SCHEMA_C2 = 126;
const OPTION_SCHEMA_C3 = 127;
const OPTION_SCHEMA_NL = 128;
const OPTION_SCHEMA_RANDOM_ONLY = 130;

const OPTION_SCHEMA_RANDOM = 0;
const OPTION_SCHEMA_1 = 1;
const OPTION_SCHEMA_2 = 2;
const OPTION_SCHEMA_3 = 3;
const OPTION_SCHEMA_4 = 4;
const OPTION_SCHEMA_5 = 5;
const OPTION_SCHEMA_6 = 6;
const OPTION_SCHEMA_7 = 7;
const OPTION_SCHEMA_8 = 8;
const OPTION_SCHEMA_9 = 9;
const OPTION_SCHEMA_10 = 10;
const OPTION_SCHEMA_11 = 11;
const OPTION_SCHEMA_12 = 12;
const OPTION_SCHEMA_13 = 13;
const OPTION_SCHEMA_14 = 14;
const OPTION_SCHEMA_15 = 15;
const OPTION_SCHEMA_16 = 16;
const OPTION_SCHEMA_17 = 17;
const OPTION_SCHEMA_18 = 18;
const OPTION_SCHEMA_19 = 19;
const OPTION_SCHEMA_20 = 20;
const OPTION_SCHEMA_21 = 21;
const OPTION_SCHEMA_22 = 22;
const OPTION_SCHEMA_23 = 23;
const OPTION_SCHEMA_24 = 24;
const OPTION_SCHEMA_25 = 25;
const OPTION_SCHEMA_26 = 26;
const OPTION_SCHEMA_27 = 27;
const OPTION_SCHEMA_28 = 28;
const OPTION_SCHEMA_29 = 29;
const OPTION_SCHEMA_30 = 30;
const OPTION_SCHEMA_31 = 31;
const OPTION_SCHEMA_32 = 32;
const OPTION_SCHEMA_33 = 33;
const OPTION_SCHEMA_34 = 34;
const OPTION_SCHEMA_35 = 35;
const OPTION_SCHEMA_36 = 36;
const OPTION_SCHEMA_37 = 37;
const OPTION_SCHEMA_38 = 38;
const OPTION_SCHEMA_39 = 39;
const OPTION_SCHEMA_40 = 40;
const OPTION_SCHEMA_41 = 41;
const OPTION_SCHEMA_42 = 42;
const OPTION_SCHEMA_43 = 43;
const OPTION_SCHEMA_44 = 44;
const OPTION_SCHEMA_45 = 45;
const OPTION_SCHEMA_46 = 46;
const OPTION_SCHEMA_47 = 47;
const OPTION_SCHEMA_48 = 48;
const OPTION_SCHEMA_49 = 49;

const OPTION_JOKER = 190;
const OPTION_JOKER_0 = 0;
const OPTION_JOKER_1 = 1;

/*
 * User preferences
 */ 
const PREF_SCHEMA_BOARD_ORDER = 100;
const PREF_SCHEMA_BOARD_ORDER_LEFT = 1;
const PREF_SCHEMA_BOARD_ORDER_RIGHT = 2;
const PREF_SCHEMA_BOARD_ORDER_LAST = 20;

const PREF_STIGMAREINE_BOARD_ORDER = 101;
const PREF_STIGMAREINE_BOARD_ORDER_LEFT = 1;
const PREF_STIGMAREINE_BOARD_ORDER_RIGHT = 2;
const PREF_STIGMAREINE_BOARD_ORDER_LAST = 20;

const PREF_STIGMAREINE_BOARD_AUTO_ORDER = 103;
const PREF_STIGMAREINE_BOARD_AUTO_ORDER_ENABLED = 1;
const PREF_STIGMAREINE_BOARD_AUTO_ORDER_DISABLED = 2;

const PREF_SP_BUTTONS = 102;
const PREF_SP_BUTTONS_IMAGES_AND_TEXT = 1;
const PREF_SP_BUTTONS_IMAGES_ONLY = 2;
const PREF_SP_BUTTONS_TEXT_ONLY = 3;


/*
 * State constants
 */
const ST_GAME_SETUP = 1;

const ST_NEXT_ROUND = 3;

const ST_FIRST_TOKEN = 4;
const ST_GENERATE_WIND = 5;
const ST_WEATHER_PLAYER_DICE = 6;

const ST_NEXT_TURN = 10;

const ST_TURN_LAST_DRIFT = 16;
const ST_TURN_CENTRAL_JOKER = 17;
const ST_TURN_CENTRAL_CHOICE_SP = 18;
const ST_TURN_CENTRAL_TOKEN_DISTRIBUTION = 19;
const ST_PLAYER_TURN = 20;
const ST_TURN_COMMON_BOARD = 21;
const ST_TURN_CENTRAL_CHOICE_TOKEN_LAND = 23;
const ST_TURN_CENTRAL_CHOICE_TOKEN_MOVE = 24;

const ST_TURN_PERSONAL_BOARD = 22;
const ST_TURN_CHOICE_TOKEN_LAND = 25;
const ST_TURN_CHOICE_TOKEN_MOVE = 26;
const ST_TURN_CHOICE_RECRUIT_CENTRAL = 27;
const ST_TURN_CHOICE_SPECIAL_ACTION = 30;
const ST_TURN_SPECIAL_ACT_MIX = 31;
const ST_TURN_SPECIAL_ACT_DIAGONAL = 32;
const ST_TURN_SPECIAL_ACT_SWAP = 33;
const ST_TURN_SPECIAL_ACT_MOVE_FAST = 34;
const ST_TURN_SPECIAL_ACT_WHITE_STEP1 =35;
const ST_TURN_SPECIAL_ACT_WHITE_STEP2 =36;
const ST_TURN_SPECIAL_ACT_BLACK_STEP1 =37;
const ST_TURN_SPECIAL_ACT_BLACK_STEP2 =38;
const ST_TURN_SPECIAL_ACT_TWOBEATS =39;
const ST_TURN_SPECIAL_ACT_REST =40;
const ST_TURN_SPECIAL_ACT_COMBINATION =41;
const ST_TURN_SPECIAL_ACT_FULGURANCE =42;
const ST_TURN_SPECIAL_ACT_CHOREOGRAPHY = 43;
const ST_TURN_SPECIAL_ACT_NSNK = 44;
const ST_TURN_SPECIAL_ACT_COPY = 45;
const ST_TURN_SPECIAL_ACT_PREDICTION = 46;
const ST_TURN_SPECIAL_ACT_MIMICRY = 47;
const ST_TURN_SPECIAL_ACT_FOGDIE = 48;
const ST_TURN_SPECIAL_ACT_PILFERER = 49;
const ST_TURN_SPECIAL_ACT_SOWER = 50;
const ST_TURN_SPECIAL_ACT_JEALOUSY = 51;

//undo these differently
const MULTIACTIVE_PRIVATE_STATES =[
    ST_TURN_CENTRAL_JOKER,
    ST_TURN_CENTRAL_CHOICE_SP,
    ST_TURN_CENTRAL_TOKEN_DISTRIBUTION,
    ST_PLAYER_TURN,
    ST_TURN_COMMON_BOARD ,
    ST_TURN_CENTRAL_CHOICE_TOKEN_LAND,
    ST_TURN_CENTRAL_CHOICE_TOKEN_MOVE,
    ST_TURN_PERSONAL_BOARD,
    ST_TURN_CHOICE_TOKEN_LAND ,
    ST_TURN_CHOICE_TOKEN_MOVE,
    ST_TURN_CHOICE_RECRUIT_CENTRAL,
    ST_TURN_CHOICE_SPECIAL_ACTION ,
    ST_TURN_SPECIAL_ACT_MIX ,
    ST_TURN_SPECIAL_ACT_DIAGONAL ,
    ST_TURN_SPECIAL_ACT_SWAP,
    ST_TURN_SPECIAL_ACT_MOVE_FAST ,
    ST_TURN_SPECIAL_ACT_WHITE_STEP1 ,
    ST_TURN_SPECIAL_ACT_WHITE_STEP2 ,
    ST_TURN_SPECIAL_ACT_BLACK_STEP1 ,
    ST_TURN_SPECIAL_ACT_BLACK_STEP2 ,
    ST_TURN_SPECIAL_ACT_TWOBEATS ,
    ST_TURN_SPECIAL_ACT_REST,
    ST_TURN_SPECIAL_ACT_COMBINATION ,
    ST_TURN_SPECIAL_ACT_FULGURANCE,
    ST_TURN_SPECIAL_ACT_CHOREOGRAPHY ,
    ST_TURN_SPECIAL_ACT_NSNK,
    ST_TURN_SPECIAL_ACT_COPY,
    ST_TURN_SPECIAL_ACT_PREDICTION,
    ST_TURN_SPECIAL_ACT_MIMICRY,
    ST_TURN_SPECIAL_ACT_FOGDIE ,
    ST_TURN_SPECIAL_ACT_PILFERER,
    ST_TURN_SPECIAL_ACT_SOWER ,
    ST_TURN_SPECIAL_ACT_JEALOUSY,
];

const ST_AFTER_TURN_NEXT_PLAYER = 70;
const ST_AFTER_TURN = 71;
const ST_AFTER_TURN_CHARMER_STEP1 = 72;

const ST_AFTER_TURN_CONFIRM_CHOICES = 78;
const ST_CONFIRM_TURN = 79;

const ST_WIND_EFFECT = 80;

const ST_END_ROUND = 85;

const ST_END_SCORING = 90;
const ST_PRE_END_OF_GAME = 98;
const ST_END_GAME = 99;


/******************
 ****** STATS ******
 ******************/
