<?php

/*
 * Game Constants
 */

const STIG_COLOR_1 = 'blue';
const STIG_PRIMARY_COLORS = [STIG_COLOR_1, ];
const STIG_COLORS = [STIG_COLOR_1, ];

const TURN_MAX = 10;

/* CARDS TYPES */

/* CARDS LOCATIONS */ 

/*
 * Game options
 */ 
const OPTION_MODE = 100;
const OPTION_MODE_DISCOVERY = 1;
const OPTION_MODE_NORMAL = 2;
const OPTION_MODE_COMPETITIVE = 3;
const OPTION_MODE_NOLIMIT = 4;

const OPTION_FLOWER = 101;
const OPTION_FLOWER_VERTIGHAINEUSE = 1;
const OPTION_FLOWER_MARONNE = 2;
const OPTION_FLOWER_SIFFLOCHAMP = 3;
const OPTION_FLOWER_DENTDINE = 4;
const OPTION_FLOWER_INSPIRACTRICE = 5;
const OPTION_FLOWER_RANDOM = 10;

const OPTION_DIFFICULTY = 102;
const OPTION_DIFFICULTY_1 = 1;
const OPTION_DIFFICULTY_2 = 2;
const OPTION_DIFFICULTY_3 = 3;
const OPTION_DIFFICULTY_4 = 4;
const OPTION_DIFFICULTY_RANDOM = 10;

const OPTION_SCHEMA_V = 110;
const OPTION_SCHEMA_M = 111;
const OPTION_SCHEMA_RANDOM = 0;
const OPTION_SCHEMA_1 = 1;
const OPTION_SCHEMA_2 = 2;
const OPTION_SCHEMA_3 = 3;
const OPTION_SCHEMA_4 = 4;
const OPTION_SCHEMA_5 = 5;
const OPTION_SCHEMA_6 = 6;
const OPTION_SCHEMA_7 = 7;
const OPTION_SCHEMA_8 = 8;
const OPTION_SCHEMA_9 = 9;
const OPTION_SCHEMA_10 = 10;
const OPTION_SCHEMA_11 = 11;
const OPTION_SCHEMA_12 = 12;
//TODO JSA OTHERS

/*
 * User preferences
 */ 
const OPTION_CONFIRM = 103;
const OPTION_CONFIRM_DISABLED = 0;
const OPTION_CONFIRM_TIMER = 1;
const OPTION_CONFIRM_ENABLED = 2;

/*
 * State constants
 */
const ST_GAME_SETUP = 1;

const ST_GENERATE_WIND = 5;
const ST_PLAYER_DICE = 6;

const ST_NEXT_TURN = 10;

const ST_PLAYER_TURN = 20;

const ST_WIND_EFFECT = 80;

const ST_END_SCORING = 90;
const ST_PRE_END_OF_GAME = 98;
const ST_END_GAME = 99;

/******************
 ****** STATS ******
 ******************/
